### ISSUE TITLE
This repository has no license.

### ISSUE THREAD

**Issue by s51517765** [middle-river/weather_station#1]
はじめまして。
私はこのリポジトリを参考（利用）してESP32でAHT25を利用したいと考えています。
しかしながら、このリポジトリにはライセンスが設定されていません。
すると、この有用なコードを再利用することができません。
もし、他の人がこれを利用することを許容する考えがありましたら適切なライセンスを設定していただけませんでしょうか？

I would like to refer to this repository and use AHT25 with ESP32.
However, this repository is not licensed.
Then this useful code cannot be reused.
If you have no intention of refusing to allow other people to use this, could you set up an appropriate license?

**Comment by middle-river** [comment]
ライセンスのご指摘いただきありがとうございました。
MITライセンスで公開したいのでLICENSEファイルを追加しました。
